[2023-12-06T10:17:08.314+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-06T10:17:08.324+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2023-12-05T00:00:00+00:00 [queued]>
[2023-12-06T10:17:08.324+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-06T10:17:08.325+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-06T10:17:08.325+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-06T10:17:08.347+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_es_info> on 2023-12-05 00:00:00+00:00
[2023-12-06T10:17:08.354+0000] {standard_task_runner.py:55} INFO - Started process 67 to run task
[2023-12-06T10:17:08.359+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'scheduled__2023-12-05T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmpz4pw_9tk']
[2023-12-06T10:17:08.361+0000] {standard_task_runner.py:83} INFO - Job 280: Subtask print_es_info
[2023-12-06T10:17:08.427+0000] {task_command.py:376} INFO - Running <TaskInstance: elastic_dag.print_es_info scheduled__2023-12-05T00:00:00+00:00 [running]> on host facebf18dc20
[2023-12-06T10:17:08.508+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2023-12-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-05T00:00:00+00:00
[2023-12-06T10:17:08.540+0000] {base.py:71} INFO - Using connection ID 'elastic_default' for task execution.
[2023-12-06T10:17:08.542+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elastic_dag.py", line 9, in _print_es_info
    print(hook.info())
AttributeError: 'ElasticHook' object has no attribute 'info'
[2023-12-06T10:17:08.564+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20231205T000000, start_date=20231206T101708, end_date=20231206T101708
[2023-12-06T10:17:08.594+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 280 for task print_es_info ('ElasticHook' object has no attribute 'info'; 67)
[2023-12-06T10:17:08.609+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-06T10:17:08.641+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
